# Generated by Django 4.2.30 on 2026-06-17 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('wallet_address', models.CharField(db_index=True, help_text='Ethereum wallet address (0x-prefixed, 42 characters).', max_length=42, unique=True)),
                ('display_name', models.CharField(blank=True, default='', help_text='Optional display name for the user.', max_length=100)),
                ('phone_number', models.CharField(blank=True, default='', help_text='Phone number for M-Pesa and SMS notifications.', max_length=20)),
                ('fcm_token', models.CharField(blank=True, default='', help_text='Firebase Cloud Messaging token for push notifications.', max_length=500)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this user account is active.')),
                ('is_staff', models.BooleanField(default=False, help_text='Whether the user can access the Django admin site.')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the account was created.')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'ordering': ['-created_at'],
            },
        ),
    ]
