# Generated by Django 4.2.30 on 2026-06-18 09:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notification_type', models.CharField(choices=[('contribution_reminder', 'Contribution Reminder'), ('loan_request', 'Loan Request'), ('loan_approved', 'Loan Approved'), ('loan_rejected', 'Loan Rejected'), ('loan_disbursed', 'Loan Disbursed'), ('payment_received', 'Payment Received'), ('member_added', 'Member Added'), ('score_updated', 'Score Updated'), ('general', 'General')], default='general', help_text='Category of this notification.', max_length=30)),
                ('title', models.CharField(help_text='Notification title (shown in push notification).', max_length=200)),
                ('body', models.TextField(help_text='Notification body text.')),
                ('data', models.JSONField(blank=True, help_text='Optional JSON payload (e.g. loan_id, circle_id).', null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed')], default='pending', help_text='Delivery status of this notification.', max_length=10)),
                ('fcm_message_id', models.CharField(blank=True, default='', help_text='FCM message ID (populated after successful send).', max_length=200)),
                ('error_message', models.TextField(blank=True, default='', help_text='Error details if delivery failed.')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this notification was created.')),
                ('user', models.ForeignKey(help_text='The user this notification was sent to.', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'notification',
                'verbose_name_plural': 'notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
