# Generated by Django 4.2.30 on 2026-06-17 12:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Circle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the circle.', primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Human-readable name for the circle.', max_length=150)),
                ('contract_address', models.CharField(blank=True, default='', help_text='On-chain contract address (populated after deployment).', max_length=42)),
                ('admin_wallet', models.CharField(help_text='Wallet address of the circle administrator.', max_length=42)),
                ('contribution_amount', models.DecimalField(decimal_places=2, help_text='Required contribution amount per period.', max_digits=18)),
                ('contribution_frequency', models.CharField(choices=[('weekly', 'Weekly'), ('biweekly', 'Biweekly'), ('monthly', 'Monthly')], default='monthly', help_text='How often members must contribute.', max_length=10)),
                ('is_active', models.BooleanField(default=True, help_text='Whether the circle is currently accepting contributions.')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the circle was created.')),
            ],
            options={
                'verbose_name': 'circle',
                'verbose_name_plural': 'circles',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LoanRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount_matic', models.DecimalField(decimal_places=4, help_text='Requested loan amount in MATIC.', max_digits=18)),
                ('reason', models.TextField(help_text='Reason / justification for the loan request.')),
                ('repayment_days', models.IntegerField(help_text='Number of days the borrower has to repay the loan.')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('disbursed', 'Disbursed'), ('repaid', 'Repaid')], default='pending', help_text='Current status of the loan request.', max_length=10)),
                ('on_chain_loan_id', models.IntegerField(blank=True, help_text='Loan ID on the smart contract (set after disbursement).', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the loan request was created.')),
                ('borrower', models.ForeignKey(help_text='The user requesting the loan.', on_delete=django.db.models.deletion.CASCADE, related_name='loan_requests', to=settings.AUTH_USER_MODEL)),
                ('circle', models.ForeignKey(help_text='The circle this loan request belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='loan_requests', to='circles.circle')),
            ],
            options={
                'verbose_name': 'loan request',
                'verbose_name_plural': 'loan requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Contribution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount contributed.', max_digits=18)),
                ('tx_hash', models.CharField(blank=True, default='', help_text='On-chain transaction hash (for crypto payments).', max_length=66)),
                ('payment_method', models.CharField(choices=[('crypto', 'Crypto'), ('mpesa', 'M-Pesa')], default='crypto', help_text='How the contribution was paid.', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the contribution was recorded.')),
                ('circle', models.ForeignKey(help_text='The circle this contribution belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='contributions', to='circles.circle')),
                ('user', models.ForeignKey(help_text='The user who made the contribution.', on_delete=django.db.models.deletion.CASCADE, related_name='contributions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'contribution',
                'verbose_name_plural': 'contributions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('member', 'Member'), ('admin', 'Admin')], default='member', help_text='Role of the user within the circle.', max_length=10)),
                ('joined_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the user joined the circle.')),
                ('circle', models.ForeignKey(help_text='The circle this membership belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='circles.circle')),
                ('user', models.ForeignKey(help_text='The user who is a member of the circle.', on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'membership',
                'verbose_name_plural': 'memberships',
                'ordering': ['-joined_at'],
                'unique_together': {('circle', 'user')},
            },
        ),
    ]
