# Generated by Django 4.2.30 on 2026-06-17 12:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('circles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MpesaPayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this payment record.', primary_key=True, serialize=False)),
                ('phone_number', models.CharField(help_text='Phone number that received the STK Push prompt (e.g. 2547XXXXXXXX).', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount in KES requested via STK Push.', max_digits=12)),
                ('merchant_request_id', models.CharField(help_text='MerchantRequestID returned by Daraja on STK Push initiation.', max_length=100)),
                ('checkout_request_id', models.CharField(db_index=True, help_text='CheckoutRequestID returned by Daraja — used to match callbacks.', max_length=100)),
                ('result_code', models.IntegerField(blank=True, help_text='ResultCode from Daraja callback (0 = success).', null=True)),
                ('result_description', models.TextField(blank=True, default='', help_text='Human-readable result description from Daraja.')),
                ('mpesa_receipt_number', models.CharField(blank=True, default='', help_text='M-Pesa transaction receipt number (populated on success).', max_length=50)),
                ('transaction_date', models.CharField(blank=True, default='', help_text='Transaction timestamp string from Daraja callback.', max_length=30)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', help_text='Current status of this payment.', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this payment record was created.')),
                ('circle', models.ForeignKey(blank=True, help_text='The savings circle this payment is associated with.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mpesa_payments', to='circles.circle')),
                ('user', models.ForeignKey(blank=True, help_text='The PayLoop user who initiated this payment.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mpesa_payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'M-Pesa payment',
                'verbose_name_plural': 'M-Pesa payments',
                'ordering': ['-created_at'],
            },
        ),
    ]
